### ISSUE TITLE
Need a Search Bar

### ISSUE THREAD

**Issue by stephin007** [stephin007/covid19-React#12]
**Is your feature request related to a problem? Please describe.**
There is no search bar in the country list dropdown

**Describe the solution you'd like**
Add a search option in the drop down.

**Comment by ethanny2** [comment]
Hi can I be assigned this issue? Also should the search bar just be submitted by a button press or I can also implement a debounced search if that fits better.

**Comment by stephin007** [comment]
Hey @ethanny2 Thankyou for showing your interest.
The search bar should be inside the drop down, please do not add any more additional component here.
and could you please explain more about debounced search?
 :)

**Comment by stephin007** [comment]
Also @ethanny2 please. leave a star ⭐ if you like it!

**Comment by ethanny2** [comment]
Okay I'll make the search bar in the dropdown. When I say debounce search I mean there is no submit button for search but rather there is a function attached to the input 's onChange that detects weather or not the user has stopped typing (something similar to getting search results on Google or Facebook's search bar) and when they have stopped typing the search will be executed without having to press a button. 

Example:
![debouncegif](https://user-images.githubusercontent.com/7098115/97478944-09478380-1928-11eb-9715-56c434f29dfe.gif)

I have a repo called react-debounce that implements this effect if you would like to see how it is implemented 
[https://github.com/ethanny2/react-debounce/blob/main/src/App2.js](url)

**Comment by stephin007** [comment]
Aah I see...got it @ethanny2   !! I also wanted the same
but here in this case I'll be typing the country name and the results should show the country name below it, and also users should have the flexibility to scroll down and click on the country they like to see the stats.

This repo is hosted, please check the link in the about section of the repo... the you will understand what is to be done

**Comment by jigs1212** [comment]
Submitted A PR for the same @stephin007 #13

**Comment by stephin007** [comment]
@jigs1212 , its working fine, just checked your branch locally!
Thankyou for contributing
