### ISSUE TITLE
Create an Interactive Readme.md

### ISSUE THREAD

**Issue by stephin007** [stephin007/covid19-React#3]
Whoever is reading this, this project has a by default Readme.md which needs to replaced by an interactive one.
For more details contact me!

**Comment by Phylis05** [comment]
Hey @stephin007, I would like to work on this.

**Comment by stephin007** [comment]
Hey @Phylis05 , Thankyou for showing interest, currently the project is in progress not much is achieved but i ll tell you what is the basic outline of this project.
Its a covid 19 tracker which shows all the countries, and in each country we are showing various data such us Active cases/Recovered Cases/ Deaths etc.

In future, I am planning to even add a page for  Precautions against covid 19.

To run the project, we need to type only npm start.

**Comment by Phylis05** [comment]
Thank you @stephin007 for this

**Comment by stephin007** [comment]
Thankyou @Phylis05 for contributing :)
