### ISSUE TITLE
Not able to get dailycases data from https://covid19.mathdro.id/api/daily

### ISSUE THREAD

**Issue by stephin007** [stephin007/covid19-React#8]
Anyone who is reading this, please suggest some other open api endpoint and change the data being invoked accordingly

**Comment by varuntumbe** [comment]
Can i try to solve this issue ?

**Comment by stephin007** [comment]
Yes PLease, let me merge my last PR!

You have to check the api folder , i am managing all my api calls from there.
YOu will find an fetchDailyData fucntion which i am calling in the Charts.js
There is a console.log in the useEffect function in the Charts.js which should log the dailyData in the console but it isnt now.
May be the API endpoint is not working anymore!

Or if there is anything else please let me know!

**Comment by varuntumbe** [comment]
Okay sure. do assign me to this after merging your last PR.
Thank You.

**Comment by stephin007** [comment]
Done @varuntumbe  Please go ahead

**Comment by varuntumbe** [comment]
Thanks!! If i get any doubts i will  post  them here.

**Comment by stephin007** [comment]
@varuntumbe any progress?

**Comment by varuntumbe** [comment]
Nope i am still trying. i will try till tomorrow then i will let you know if you're okay

**Comment by stephin007** [comment]
Great, no issues take your time! @varuntumbe

**Comment by stephin007** [comment]
@varuntumbe any progress, or else i will close this issue!

**Comment by varuntumbe** [comment]
sorry for the late reply. i am not getting it. you can assign it to some else.
Thanks
